### ISSUE TITLE
SyntaxError: Unexpected token export after upgrading to version 4.0.4

### ISSUE THREAD

**Issue by mupakoz** [chaijs/type-detect#123]
Hello! After upgrading to version 4.0.4 I cannot run my mocha tests anymore. I am getting SyntaxError: Unexpected token export on the index.js file of the type-detect. Here is the full stack:

C:\Tools\nodejs\node.exe "<mypath>\node_modules\mocha\bin\_mocha" --ui bdd --reporter C:\Users\taakopa7\.IntelliJIdea2017.2\config\plugins\NodeJS\js\mocha-intellij\lib\mochaIntellijReporter.js "<mypath>\test\mytest.js" --grep "Test "
<mypath>\node_modules\type-detect\index.js:49
export default function typeDetect(obj) {
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<mypath>\node_modules\chai\lib\chai\utils\index.js:23:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<mypath>\node_modules\chai\lib\chai.js:25:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<mypath>\node_modules\chai\index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<mypath>\test\mytest.js:2:12)

**Comment by vieiralucas** [comment]
Hello @mupakoz, v4.0.5 just got released and should fix that. Sorry for the mess

**Comment by pabigot** [comment]
Actually, I gotta retract the thumbs up.  master fails to pass unit tests on node 4.5.0 with the same error.  Seems to be because 8ec24272d6733fae7954fc0 was a little too aggressive in adding ES6 support.

**Comment by mupakoz** [comment]
It helped with my problem.

**Comment by pabigot** [comment]
Sorry, I was too fast with the diagnosis.  master does seem to fail to pass unit tests with node 4.5.0, but with a different error.  This fix does allow a fresh reinstall of sinon/mocha to work.
