### ISSUE TITLE
Release v4.0.5 needs ES6 modules syntax?

### ISSUE THREAD

**Issue by reod** [chaijs/type-detect#125]
During my build I'm getting:
```
/usr/src/app/node_modules/type-detect/index.js:49
export default function typeDetect(obj) {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

It's intentional? Because it seems like huge change, not a minor patch – `v4.0.3` used old module syntax.

**Comment by keithamus** [comment]
Could you tell me are you actually using type-detect 4.0.5? It works fine for me on fresh installs in both yarn and npm. Are you using a build system?

**Comment by amiram** [comment]
I'm using chai 4.1.2 with node 6.12.0. type-detect 4.0.4 and I have this error too.

**Comment by keithamus** [comment]
@amiram please update to type-detect 4.0.5.

**Comment by Mattenable** [comment]
I'm not explicitly using type-detect, just chai 4.1.2, and am having this same issue

**Comment by keithamus** [comment]
Could you please try `npm i -D chai@4.1.2` to see if it fixes the problem.

**Comment by Mattenable** [comment]
@keithamus ran that command. problem persists

**Comment by keithamus** [comment]
@Mattenable please try `npm rm chai; npm i -D chai@4.1.2`

**Comment by Mattenable** [comment]
no luck. I'll try to come up with a simple test to share

**Comment by amiram** [comment]
4.0.5 is working. You have to delete chai and type-detect folders from node_modules and install chai again

**Comment by Mattenable** [comment]
@keithamus I made this:
https://github.com/Mattenable/chaitest

Just clone, npm install, npm run test

**Comment by vieiralucas** [comment]
Hello @Mattenable I tried to reproduce with your repo
I got this:
![image](https://user-images.githubusercontent.com/7764293/32613347-d2d1dd00-c551-11e7-93bf-8a5274c94b9e.png)
My package-lock.json
```
{
  "name": "chaitest",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "assertion-error": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.2.tgz",
      "integrity": "sha1-E8pRXYYgbaC6xm6DTdOX2HWBCUw=",
      "dev": true
    },
    "balanced-match": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz",
      "integrity": "sha1-ibTRmasr7kneFk6gK4nORi1xt2c=",
      "dev": true
    },
    "brace-expansion": {
      "version": "1.1.8",
      "resolved": "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz",
      "integrity": "sha1-wHshHHyVLsH479Uad+8NHTmQopI=",
      "dev": true,
      "requires": {
        "balanced-match": "1.0.0",
        "concat-map": "0.0.1"
      }
    },
    "browser-stdout": {
      "version": "1.3.0",
      "resolved": "https://registry.npmjs.org/browser-stdout/-/browser-stdout-1.3.0.tgz",
      "integrity": "sha1-81HTKWnTL6XXpVZxVCY9korjvR8=",
      "dev": true
    },
    "chai": {
      "version": "4.1.2",
      "resolved": "https://registry.npmjs.org/chai/-/chai-4.1.2.tgz",
      "integrity": "sha1-D2RYS6ZC8PKs4oBiefTwbKI61zw=",
      "dev": true,
      "requires": {
        "assertion-error": "1.0.2",
        "check-error": "1.0.2",
        "deep-eql": "3.0.1",
        "get-func-name": "2.0.0",
        "pathval": "1.1.0",
        "type-detect": "4.0.5"
      }
    },
    "check-error": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/check-error/-/check-error-1.0.2.tgz",
      "integrity": "sha1-V00xLt2Iu13YkS6Sht1sCu1KrII=",
      "dev": true
    },
    "commander": {
      "version": "2.11.0",
      "resolved": "https://registry.npmjs.org/commander/-/commander-2.11.0.tgz",
      "integrity": "sha512-b0553uYA5YAEGgyYIGYROzKQ7X5RAqedkfjiZxwi0kL1g3bOaBNNZfYkzt/CL0umgD5wc9Jec2FbB98CjkMRvQ==",
      "dev": true
    },
    "concat-map": {
      "version": "0.0.1",
      "resolved": "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz",
      "integrity": "sha1-2Klr13/Wjfd5OnMDajug1UBdR3s=",
      "dev": true
    },
    "debug": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz",
      "integrity": "sha512-OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==",
      "dev": true,
      "requires": {
        "ms": "2.0.0"
      }
    },
    "deep-eql": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/deep-eql/-/deep-eql-3.0.1.tgz",
      "integrity": "sha512-+QeIQyN5ZuO+3Uk5DYh6/1eKO0m0YmJFGNmFHGACpf1ClL1nmlV/p4gNgbl2pJGxgXb4faqo6UE+M5ACEMyVcw==",
      "dev": true,
      "requires": {
        "type-detect": "4.0.5"
      }
    },
    "diff": {
      "version": "3.3.1",
      "resolved": "https://registry.npmjs.org/diff/-/diff-3.3.1.tgz",
      "integrity": "sha512-MKPHZDMB0o6yHyDryUOScqZibp914ksXwAMYMTHj6KO8UeKsRYNJD3oNCKjTqZon+V488P7N/HzXF8t7ZR95ww==",
      "dev": true
    },
    "escape-string-regexp": {
      "version": "1.0.5",
      "resolved": "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz",
      "integrity": "sha1-G2HAViGQqN/2rjuyzwIAyhMLhtQ=",
      "dev": true
    },
    "fs.realpath": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz",
      "integrity": "sha1-FQStJSMVjKpA20onh8sBQRmU6k8=",
      "dev": true
    },
    "get-func-name": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/get-func-name/-/get-func-name-2.0.0.tgz",
      "integrity": "sha1-6td0q+5y4gQJQzoGY2YCPdaIekE=",
      "dev": true
    },
    "glob": {
      "version": "7.1.2",
      "resolved": "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz",
      "integrity": "sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ==",
      "dev": true,
      "requires": {
        "fs.realpath": "1.0.0",
        "inflight": "1.0.6",
        "inherits": "2.0.3",
        "minimatch": "3.0.4",
        "once": "1.4.0",
        "path-is-absolute": "1.0.1"
      }
    },
    "growl": {
      "version": "1.10.3",
      "resolved": "https://registry.npmjs.org/growl/-/growl-1.10.3.tgz",
      "integrity": "sha512-hKlsbA5Vu3xsh1Cg3J7jSmX/WaW6A5oBeqzM88oNbCRQFz+zUaXm6yxS4RVytp1scBoJzSYl4YAEOQIt6O8V1Q==",
      "dev": true
    },
    "has-flag": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/has-flag/-/has-flag-2.0.0.tgz",
      "integrity": "sha1-6CB68cx7MNRGzHC3NLXovhj4jVE=",
      "dev": true
    },
    "he": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/he/-/he-1.1.1.tgz",
      "integrity": "sha1-k0EP0hsAlzUVH4howvJx80J+I/0=",
      "dev": true
    },
    "inflight": {
      "version": "1.0.6",
      "resolved": "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz",
      "integrity": "sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=",
      "dev": true,
      "requires": {
        "once": "1.4.0",
        "wrappy": "1.0.2"
      }
    },
    "inherits": {
      "version": "2.0.3",
      "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz",
      "integrity": "sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=",
      "dev": true
    },
    "minimatch": {
      "version": "3.0.4",
      "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz",
      "integrity": "sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==",
      "dev": true,
      "requires": {
        "brace-expansion": "1.1.8"
      }
    },
    "minimist": {
      "version": "0.0.8",
      "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz",
      "integrity": "sha1-hX/Kv8M5fSYluCKCYuhqp6ARsF0=",
      "dev": true
    },
    "mkdirp": {
      "version": "0.5.1",
      "resolved": "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz",
      "integrity": "sha1-MAV0OOrGz3+MR2fzhkjWaX11yQM=",
      "dev": true,
      "requires": {
        "minimist": "0.0.8"
      }
    },
    "mocha": {
      "version": "4.0.1",
      "resolved": "https://registry.npmjs.org/mocha/-/mocha-4.0.1.tgz",
      "integrity": "sha512-evDmhkoA+cBNiQQQdSKZa2b9+W2mpLoj50367lhy+Klnx9OV8XlCIhigUnn1gaTFLQCa0kdNhEGDr0hCXOQFDw==",
      "dev": true,
      "requires": {
        "browser-stdout": "1.3.0",
        "commander": "2.11.0",
        "debug": "3.1.0",
        "diff": "3.3.1",
        "escape-string-regexp": "1.0.5",
        "glob": "7.1.2",
        "growl": "1.10.3",
        "he": "1.1.1",
        "mkdirp": "0.5.1",
        "supports-color": "4.4.0"
      }
    },
    "ms": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz",
      "integrity": "sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g=",
      "dev": true
    },
    "once": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/once/-/once-1.4.0.tgz",
      "integrity": "sha1-WDsap3WWHUsROsF9nFC6753Xa9E=",
      "dev": true,
      "requires": {
        "wrappy": "1.0.2"
      }
    },
    "path-is-absolute": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz",
      "integrity": "sha1-F0uSaHNVNP+8es5r9TpanhtcX18=",
      "dev": true
    },
    "pathval": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/pathval/-/pathval-1.1.0.tgz",
      "integrity": "sha1-uULm1L3mUwBe9rcTYd74cn0GReA=",
      "dev": true
    },
    "supports-color": {
      "version": "4.4.0",
      "resolved": "https://registry.npmjs.org/supports-color/-/supports-color-4.4.0.tgz",
      "integrity": "sha512-rKC3+DyXWgK0ZLKwmRsrkyHVZAjNkfzeehuFWdGGcqGDTZFH73+RH6S/RDAAxl9GusSjZSUWYLmT9N5pzXFOXQ==",
      "dev": true,
      "requires": {
        "has-flag": "2.0.0"
      }
    },
    "type-detect": {
      "version": "4.0.5",
      "resolved": "https://registry.npmjs.org/type-detect/-/type-detect-4.0.5.tgz",
      "integrity": "sha512-N9IvkQslUGYGC24RkJk1ba99foK6TkwC2FHAEBlQFBP0RxQZS8ZpJuAZcwiY/w9ZJHFQb1aOXBI60OdxhTrwEQ==",
      "dev": true
    },
    "wrappy": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz",
      "integrity": "sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8=",
      "dev": true
    }
  }
}
```

**Comment by Mattenable** [comment]
I'm running node 6. do I need to update to 8 to use this package?

**Comment by vieiralucas** [comment]
No, `type-detect` should work with node >= 4
![image](https://user-images.githubusercontent.com/7764293/32613587-809c4e34-c552-11e7-8131-b477ad0b8b88.png)

**Comment by keithamus** [comment]
@Mattenable if you have a `package-lock.json` you'll need to run `npm rm chai` and maybe `npm rm type-detect` to clear it out of your lockfile. In a few hours we'll release `chai@4.1.5` which will absolutely fix the issue, so if you can wait just a few hours we'll have this fixed.

**Comment by keithamus** [comment]
BTW I have unpublished `4.0.4` (the irony of which is not lost on me)

```
npm i type-detect@4.0.4                                                                                                                                                                 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for type-detect@4.0.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Mattenable** [comment]
lol

I did notice, however, that chai 4.1.2 is pulling down type-detect 4.0.4 instead of 4.0.5. I think this is an issue with my organization's internal nexus repo :( when i `npm set registry=https://registry.npmjs.org/` everything works. Sorry for the trouble

**Comment by meeber** [comment]
@keithamus @vieiralucas Thanks for handling this crisis so quickly. Sorry I can't be of much help during business hours.

**Comment by vieiralucas** [comment]
That was mostly @keithamus by the way.
I was here just responding issues while he was fighting travis. 😸

**Comment by keithamus** [comment]
I'm going to close this issue; I'm pretty sure we've resolved this. If anyone else has any issues please feel free to comment (or raise a new issue) and we can look into it.
