### ISSUE TITLE
It fails with `yarn`

### ISSUE THREAD

**Issue by MichaelOrtho** [chaijs/type-detect#126]
I did `chai` with `yarn` (`yarn add chai -D`) and it pulled `type-detect` v4.0.5. After that it breaks on `mocha` as it is not transpiled. I did same with `npm install` and it worked. I see transpiled file.

It is Node.JS v8.9.1, npm v5.5.1, yarn v1.2.1

```
export default function typeDetect(obj) {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

Advice?

**Comment by keithamus** [comment]
In `4.0.5`? It should use the `main` field.

**Comment by keithamus** [comment]
Let's close this one and focus the discussion in #124
